"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%6k*u9jzz$yyu-##81*v9m@im#lz5bbw(of1df_6-ig=0*22ca"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "movie",
    "rest_framework",
    "django_filters",
    "djoser",
    "account",
    "trade",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "drf_movie",
        "USER": "root",
        "PASSWORD": "root",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = "zh-hans"
LOCALE_PATHS = [
    Path(BASE_DIR).joinpath("locale"),
]

# TIME_ZONE = 'UTC'
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 9,
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# 配置JWT
from datetime import timedelta

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("JWT",),
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=20),  # 设置访问令牌的生命周期
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),  # 设置刷新令牌的生命周期
}

# 邮箱配置
# XQZx7SMNWLJTYN65
EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = "littleapp_a@163.com"
EMAIL_HOST_PASSWORD = "XQZx7SMNWLJTYN65"
DEFAULT_FROM_EMAIL = "littleapp_a@163.com"


# Djoser配置
DJOSER = {
    "USER_ID_FIELD": "username",
    "LOGIN_FIELD": "email",
    "SEND_ACTIVATION_EMAIL": True,
    "ACTIVATION_URL": "activate/{uid}/{token}",
    "SEND_CONFIRMATION_EMAIL": True,
    "PASSWORD_RESET_CONFIRM_URL": "password_reset/{uid}/{token}",
    "PASSWORD_RESET_CONFIRM_RETYPE": True,
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": True,
    "SET_PASSWORD_RETYPE": True,
    "SERIALIZERS": {
        "user_create": "account.serializers.CustomUserCreateSerializer",
        "current_user": "account.serializers.CustomUserSerializer",
    },
}

# 配置支付宝
# 支付宝网关地址
ALIPAY_SERVER_URL = 'https://openapi-sandbox.dl.alipaydev.com/gateway.do'
# 应用APPID
ALIPAY_APP_ID = '9021000132652020'
# 应用私钥
ALIPAY_APP_PRIVATE_KEY = 'MIIEowIBAAKCAQEA08ROThVTWlEamgO3xB8hdGf6qull4mWoSYsAEP8E86czTV8GKP+MgEq5Yfc1RA80gk9q7GmZj0YeDncVBs6RH92noi13MTTGcgYvIiJvdggxUDO3yzQSfp55Whf5nGcVHJBaEwBDEZ4qSaTcsCmqGwBhSruaX0qNZOib+TYmeeoOz8oWakGI5OAmc8YbDAHFs3nIXz9mB5AQr/bX0mBViEjBeuFoAXCABd82m5iFv7poL3vAHKsL/wpzw23igEOCz8xqsli5rTqE550uWwiQqdGG8gh5WwvWdI1xxPzBAXp6Jiozcj+6886L2dobQE9X8JYbSQ6ZvFWm1O4j72+/DQIDAQABAoIBAE/CpGushJSD760KsXBg+UzKzRMKjaFUAKqSfBfqtYa/9waxP7S5a8X2XxSS87EKuRBLsU4SCBB6rF9uYrEJpIeICNeAoGAcLJJN2frVVX3zX/+BOzyCBGVEcxiH5zANc1oq1IJLmvdLx0mtmqGPT86TuhFXz7EMd20GX5jh2GQaIAW8c8dDQH7JbWXA5gjR+RjrUOv1O1YBKeyi4iuW4Fa+BS0A8aP4seytjCUbgD6Pk2WQSikwPcaBGSr3Ft+44yv2VPqyD7wCMYV8T1to0MOeDuJh1LvooaFGehlU7IZOhtfYe9SK+9I87+U+x8Xv8ycP35jW+Pr3KuJBFHlldNECgYEA/9c6+Uumghg1AkG6vwZTZNuYrCrx8CMlI70iVibunVkaUXUHwsHm7UCNAmTYBijfHAl3dC3wJnYgi5bnGtaV5gjPbCOb1TosYsT7cCVmR2R+FLVllcjIzBTvOcLP0aVwxamjEQjV2Y7jE1deR9oJQ85pz25lhZ6kv4wl28+awuMCgYEA0+YNVb+obbN3sukCEbS0H+6Gh90fITsIJuzOdlGepdTYcPyznk+RT60kJdUvNMWHRXUsFT2mX2Mssz099K+Hqmq2IRp3lppyAwZ8hdXNorTjvpBC5z7SmhjYOGziKTJbIHyzZs8QBYOxfrWwatn5/CpwQvgWdDcT8u06C4gP6U8CgYBsL1ZXzt6lSpk30BWo64LeNmH0A+D029e7qiHX7nSeguw3H9bdS2NcVhyKs5wJ1sSptXMW5MoVaYRPosstNSqD8JvNra0a2JOmXIe6n4YFkIAkP6SqVxJaAkw6z59TlrL+UsKK1IKhkeOB7UMH/TJHwwRJW/SAMVqXSStFLR/TYwKBgBGux/wY41hMOrfuY+LQXpuvjwB1fmyKfZKp/ky3YPLbwTgkjmSupSSuAS87DBZuSWyNa6FWJLUfFJLckHgD0eFxyEMY71PdDZidCPUuM1vZlovHhB3CC1carah/xZvEfQBIB7yTmPWs2LoHNXKlQAxACmA8TbtjAUIrc8WUlCdXAoGBAMccrBKtFD6v0VaSuEC7SAhMdDYw4K2RPHk6y7iOfxyyWpNPGYTSayX0iBbADxFVlyzbEKjnTfGDAhodmllwhumDpGdu6j7KEVlRLQ0f42VHcwRvK86JHmSGtoob1aqJOT2hvZs3kZYdwalO7y50JgkEJpldROVeL3f2qwKBFexc'
# 支付宝公钥
ALIPAY_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtAiCSOOkRwq2n1J/wGu3uO7wkgECSQhGAGN8w39mJJgBqmSksTzlwi+5lan7Q48j69aOHGw0y0pY4aUhyt3ZXXfIDI9CQA1OhOFxHvJtYyh2mZFJwC6F2qhEeW85SvcscQLO9FIBtjCgsAbPG7km0+MpJ5WkCpV4JFXOmSgOTHTxq9HEMSmId/hkVpVdwxoEw1on6Ffn6fxmHPArZ/xNJskarEuRSr+/FH+a1PXuwS9v/D7d5WjruVJxKFLhoAcXFRhr8JQbpv2cuMjDuxxnDpJJOjAnmtjPet+RMvdc7USiTvDkVCVJEw1oPKj9C2iJhLHXbNmJ03A+Ui9rmjL0iQIDAQAB'
#returnURL
ALIPAY_RETURN_URL = 'http://480cf1ec.r27.cpolar.top/orders/'
#NotifyURL
ALIPAY_NOTIFY_URL = 'http://480cf1ec.r27.cpolar.top/api/callback/'
#seller_id
ALIPAY_SELLER_ID = '2088721023502536'


# 配置Celery
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/1"
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60