# Generated by Django 4.2.4 on 2025-05-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='update_info',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='update_progress',
        ),
    ]
