# Generated by Django 4.2.4 on 2025-05-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_subtitle_remove_movie_update_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='alternate_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='region',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='scriptwriter',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='types',
        ),
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='author_info',
            field=models.CharField(default='', max_length=100, verbose_name='作者简介'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='catalogue',
            field=models.CharField(default='', max_length=100, verbose_name='目录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='course_name',
            field=models.CharField(default='', max_length=100, verbose_name='课程名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(blank=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='发布日期'),
        ),
    ]
