# Generated by Django 4.2.4 on 2025-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='author_info',
            field=models.TextField(max_length=300, verbose_name='作者简介'),
        ),
    ]
